/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import junit.framework.TestCase;
import scenario.MovingImage;
import util.XMLConfig;

import java.awt.*;


public class MovingImageTest extends TestCase {
    private MovingImage movingImage;
    @Override
    protected void setUp() throws Exception {
        movingImage = new MovingImage(
                new XMLConfig("src/main/resources/config.xml").getConfig().getElementsByTagName("image"));
    }
    public void testMovingImageGetImages() {
        assertTrue(movingImage.getImages().size() > 0);
    }

}
