/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import junit.framework.TestCase;
import org.w3c.dom.Document;
import util.XMLConfig;


public class XMLConfigTest extends TestCase {
    private XMLConfig xmlConfig;
    private String pathname = "src/main/resources/config.xml";
    @Override
    protected void setUp() throws Exception {
        xmlConfig = new XMLConfig(
                this.pathname
        );
    }
    public void testXMLConfigHasGetConfig() {
        Document config = XMLConfig.loadConfig(this.pathname);
        xmlConfig.setConfig(config);
        assertEquals(config, xmlConfig.getConfig());
    }
}
